Update tests to use node:test, remove tap
fastify/fastify-secure-session pull request #235
Opened 2024-09-11 09:57 UTC by bencoder

Updates tests to use node:test
Remove tap
Converted tests to async/await style over callbacks and removed `t.plan(x)` statements where appropriate

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-09-11 10:05 UTC, Uzlopak commented
Yeah the windows fails. Maybe simplest solution: change file extensions of all test files from `.js` to `.test.js`

2024-09-11 10:14 UTC, gurgunday requested changes
Hi, thanks a lot for the PR!

Please:

1) Install `c8`
2) Change the `test:unit` command to `c8 --100 node --test`
3) As @Uzlopak said, for consistency, it would be great if you could add `.test.` to the test files

2024-09-11 14:05 UTC, dancastillo reviewed
Can you add back the `t.plan` to the tests `node:test` does support test count assertions [ref](https://nodejs.org/api/test.html#contextplancount)

2024-09-11 14:13 UTC, bencoder commented
@dancastillo I've removed them where they are not adding anything - they only really make sense when you have assertions in callbacks or conditional statements - everywhere I've removed them has been where I've changed to using `await` so the assertions will always run and setting `t.plan` just seems like extra friction. 

If they should be a standard for fastify tests though then I can add them back if necessary

2024-09-12 01:53 UTC, dancastillo commented
@bencoder That makes sense to me! As for the standard with Fastify tests, I believe we have them in place for most of our tests but like you mention likely for callbacks or conditionals

I'll defer it to @Uzlopak or @gurgunday to confirm whether it's a strict requirement or is okay

2024-09-12 02:00 UTC, jsumners commented
I would reserve plans for tests of asynchronous operations.

2024-09-15 10:22 UTC, gurgunday approved these changes
lgtm

2024-09-15 13:35 UTC, dancastillo commented on test/access.test.js
> +  t.assert.ifError(postResponse.error)
```suggestion
  t.assert.ok(postResponse)
```

2024-09-15 13:36 UTC, dancastillo commented on test/access.test.js
> +  t.assert.ifError(getResponse.error)
```suggestion
  t.assert.ok(getResponse)
```

2024-09-15 13:36 UTC, dancastillo reviewed
Looks like there is no `error` defined on `await fastify.inject(...)` response [ref](https://github.com/fastify/light-my-request/blob/master/types/index.d.ts#L78-L93)

So this below will never fail. 
```js
t.assert.ifError(response.error)
```

Can we update all similar asserts to below to validate we received a truthy response
```js
  t.assert.ok(response)
```

2024-09-15 16:39 UTC, dancastillo approved these changes
LGTM

2024-09-15 16:40 UTC, merged